### ISSUE TITLE
work on scanner/login page

### ISSUE THREAD

**Issue by srujant** [gotechnica/technica-mobile-app#12]
--assigned to Srujan Thotapally
--work on displaying qr code
--a scanning capability presents itself if admin

**Comment by ng-david** [comment]
@srujant i dont recall, are you still working on scanner or is that part of the person doing profile

**Comment by ng-david** [comment]
@srujant how's it going

**Comment by Andrewjeska** [comment]
@ng-david  @srujant  I've done most of that, the question is generating QR codes. Also I don't know how to get camera permissions to work
