### ISSUE TITLE
Build Schedule + Saved

### ISSUE THREAD

**Issue by ng-david** [gotechnica/technica-mobile-app#13]
Should have two inner tabs (like the bitcamp app)
Look closely at the design doc for details :)

Feel free to add more to this ticket to help you keep track of what needs to be done:

**Comment by ng-david** [comment]
hows it going my dude

**Comment by robotal** [comment]
it's going great

**Comment by ng-david** [comment]
Note to self: 

We need to make the big times stronger (maybe a color?) because they feel lost in the white mess right now

We should grey out events that have passed to alleviate the white mess

Maybe we should highly the current chunk? Outline in pink? Maybe the previous ^ fix will make this fix seem redundant and unnecessary?

We need to optimize the schedule somehow? Maybe we can make an APK build first and see if that feels just as bad as the dev builds. If not major, nbd.
